# Generated by Django 3.1.6 on 2021-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210214_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shopadmin',
            field=models.BooleanField(default=False),
        ),
    ]
