# Generated by Django 3.1.6 on 2021-02-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_is_subcat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
