# Generated by Django 3.1.6 on 2021-02-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status', '-created']},
        ),
    ]
