# Generated by Django 3.1.6 on 2021-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210227_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['is_paid', 'status', '-created']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_send',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'on proccess'), ('s', 'sent'), ('o', 'out of Storage'), ('w', 'Waiting')], default='w', max_length=1),
        ),
    ]
